### PR TITLE
Carbonated/recastnavigation

### PR DESCRIPTION
**Pull request by alexeykostin**
## What does this PR do?

1. Added new functionality required for our AI implementation
2. Fixed the discrepancy between sync and async geometry collection
3. Minor bug fixes

## How was this PR tested?

_Please describe any testing performed._

### CODE REVIEW

**Review by JDACarbonated — APPROVED** [review]
Most all of the #if defined(CARBONATED) changes are core features that need to be integrated back into O3DE. Something for that team to do at a later date.

**Review by Twolewis — APPROVED** [review]

**Comment by Twolewis** [comment]
@alexeykostin  - do we need to wait on the kyt removal branch before merging this in?

**Comment by alexeykostin** [comment]
> @alexeykostin - do we need to wait on the kyt removal branch before merging this in?

@Twolewis These changes won't be in use in the current code. We don't need to wait.

**Comment by Twolewis** [comment]
@alexeykostin  - then please test these against on the project dev branch, and if it all works as expected, feel free to merge to engine dev.

**Comment by alexeykostin** [comment]
> @alexeykostin - then please test these against on the project dev branch, and if it all works as expected, feel free to merge to engine dev.

Checked using Jenkins `build/akostin/dev`

**Pull request merged**
