### PR TITLE
Revert legacy pNetwork in SSystemGlobalEnvironment

### PR DESCRIPTION
**Pull request by alexeykostin**
## What does this PR do?

Revert legacy pNetwork in SSystemGlobalEnvironment as it is the most relevant structure for such a singleton.

## How was this PR tested?

Built locally

### CODE REVIEW

**Review by vmednonogov — APPROVED** [review]
LGTM
(Could you add a short comment with description why you have to add pNetwork here)

**Review by VladimirLagutin — APPROVED** [review]
LGTM

**Comment by vmednonogov** [comment]
@alexeykostin could you add deinitialization into the void CSystem::ShutDown(), where other things are deinitialized?

**Comment by alexeykostin** [comment]
> @alexeykostin could you add deinitialization into the void CSystem::ShutDown(), where other things are deinitialized?

Added.

**Comment by vmednonogov** [comment]
@alexeykostin ok

**Pull request merged**
