### PR TITLE
[ImGui] Optionally manage only owned on-screen keyboard

### PR DESCRIPTION
**Pull request by alexeykostin**
## What does this PR do?

This PR allows to work around the issue when, while entering a text input, the user enables an ImGui window. In our case, this is the thread profiler. Previous behavior turned off the on-screen keyboard after showing the thread profiler window and thus blocked the game flow.

The new behavior makes difference between on-screen keyboard a) enabled by ImGui and b) the client, e.g. UICanvasTextInput. In the (a) case ImGui manages the on-screen keyboard as it used to do. In the (b) case the client continues to manage its input.

## How was this PR tested?

Tested locally, iPhone + RemoteConsole.

### CODE REVIEW

**Review by vmednonogov — APPROVED** [review]
LGTM.
Approved with a question:
Should we set io.AffectGlobalTextInput to TRUE somewhere?

**Comment by alexeykostin** [comment]
> Should we set io.AffectGlobalTextInput to TRUE somewhere?

AffectGlobalTextInput was helpful for debugging. I've just removed it.

**Comment by Twolewis** [comment]
@alexeykostin - please run this by the discord folks to get their thoughts as well, and whether or not we should get this into the main engine

**Comment by Twolewis** [comment]
@JDACarbonated - please try this out on your machine when you get a chance.  Just switch to this engine branch, build editor etc, and see if it works as expected!

**Comment by JDACarbonated** [comment]
I tried to sync to md-15807-vkeyboard and build but I'm getting multiple build errors. I ran the CMake configure / generate. Is there something else I need to run?

`9>C:\dev\o3de\Code\Framework\AzCore\AzCore\Debug\Trace.cpp(606,17): error C2509: 'OutputToRawAndDebugger': member function not declared in 'AZ::Debug::Trace'
9>    void Trace::OutputToRawAndDebugger(const char* window, const char* message)
9>                ^ (compiling source file 'CMakeFiles/AzCore.dir/Unity/unity_3_cxx.cxx')
9>C:\dev\o3de\Code\Framework\AzCore\AzCore\Debug\Trace.h(142,15):
9>see declaration of 'AZ::Debug::Trace'
9>        class Trace
9>              ^
9>C:\dev\o3de\Code\Framework\AzCore\AzCore\Asset\AssetManager.cpp(338,17): error C2220: the following warning is treated as an error
9>            int currentWaitForAssetUpdate = MaxWaitForAssetUpdateMs;
9>                ^ (compiling source file 'CMakeFiles/AzCore.dir/Unity/unity_0_cxx.cxx')
`

**Comment by Twolewis** [comment]
> I tried to sync to md-15807-vkeyboard and build but I'm getting multiple build errors. I ran the CMake configure / generate. Is there something else I need to run?
> 
> `9>C:\dev\o3de\Code\Framework\AzCore\AzCore\Debug\Trace.cpp(606,17): error C2509: 'OutputToRawAndDebugger': member function not declared in 'AZ::Debug::Trace' 9> void Trace::OutputToRawAndDebugger(const char* window, const char* message) 9> ^ (compiling source file 'CMakeFiles/AzCore.dir/Unity/unity_3_cxx.cxx') 9>C:\dev\o3de\Code\Framework\AzCore\AzCore\Debug\Trace.h(142,15): 9>see declaration of 'AZ::Debug::Trace' 9> class Trace 9> ^ 9>C:\dev\o3de\Code\Framework\AzCore\AzCore\Asset\AssetManager.cpp(338,17): error C2220: the following warning is treated as an error 9> int currentWaitForAssetUpdate = MaxWaitForAssetUpdateMs; 9> ^ (compiling source file 'CMakeFiles/AzCore.dir/Unity/unity_0_cxx.cxx') `

This looks unrelated to this PR, especially since the compiler error comes from AssetManager.cpp.   How are you configuring?  Are you using the carb.sh project configure?

**Comment by JDACarbonated** [comment]
Git Bash to launch cmake in the O3DE build/windows directory then running Configure then Generate. Let me try via script.

**Comment by JDACarbonated** [comment]
How do I run the script in the O3DE directory? There is no ./carb.sh

**Review by Twolewis — APPROVED** [review]

**Comment by Twolewis** [comment]
@JDACarbonated , @alexeykostin  - what's left here?

**Review by JDACarbonated — APPROVED** [review]

**Pull request merged**
