### PR TITLE
RAM Reduction: Remove Legacy Asset Mapping

### PR DESCRIPTION
**Pull request by AMZN-Gene**
- Removes a large mapping of legacy asset ids from the game and editor runtime. This map contains a "legacy" UUIDs dating from the Lumberyard days (prior to O3DE's existence in 2021). Each asset's legacy-type uuid is stored and so grows linearly as games add more assets. 
- Also removes legacy asset id's from the SQL database saved to disk

## How was this PR tested?
Ran MadWorld ensuring in-game entities and menus still load.

### CODE REVIEW

**Comment by carbonated-niko** [comment]
Is this something that is getting folded back into o3de and were just guinea pigging the removal?

**Review by carbonated-niko — APPROVED** [review]

**Comment by AMZN-Gene** [comment]
> Is this something that is getting folded back into o3de and were just guinea pigging the removal?

Hope to fold this one back! O3DE cannot pull the rug out from under people, so for the next release we'll add some print warnings whenever using old asset ids. 
https://github.com/carbonated-dev/o3de/pull/238

**Comment by carbonated-niko** [comment]
Makes sense, and lgtm!

**Review by Twolewis — APPROVED** [review]

**Comment by AMZN-Gene** [comment]
FBX failing to compile after removing legacy sub-ids from the SQL. 
Created a [smaller PR here](https://github.com/carbonated-dev/o3de/pull/239) that'll remove the runtime maps without any issues... will reopen as a 2nd PR.

**Pull request closed without merging**
