### PR TITLE
Promote tonemapping half float to full float

### PR DESCRIPTION
**Pull request by akioCL**
## What does this PR do?

Promote tonemapping half float to full float to avoid NaNs

## How was this PR tested?

PC

### CODE REVIEW

**Review by moudgils — APPROVED** [review]
I thought this work was already merged but maybe I am wrong. This PR should just contain the real->float change.

**Comment by akioCL** [comment]
> I thought this work was already merged but maybe I am wrong. This PR should just contain the real->float change.

It was merged but it was reverted because of NaN issues. I promoted to full float values, but AFAIK nobody has tested to see if it fixed the NaN issues.

**Comment by Twolewis** [comment]
I'll make a build today to take a look

**Comment by Twolewis** [comment]
iOS build looks good!  Merge at your pleasure, @akioCL !

**Review by Twolewis — APPROVED** [review]

**Comment by akioCL** [comment]
> iOS build looks good! Merge at your pleasure, @akioCL !

Thanks for checking!

**Pull request merged**
