### PR TITLE
Change shader option indices container

### PR DESCRIPTION
**Pull request by aefimov3**
## Change description

Change shader option indices container to a more effective version.
It does not allocate memory.
It works much faster.
The capacity is limited, it supports indices up to 128. Typically in the game it is under 64. The index grows sequentially.

## Tested

Local tests on PC standalone build.

### CODE REVIEW

**Comment by JasonCarbonated** [comment]
Does this mean at most in the game we can have 128 discrete shaders for all materials? Or each material can have at most 128 shaders applied? Are we hard limited to having only 128 different shaders?

**Review by JasonCarbonated — APPROVED** [review]
Approved, but with question.

**Review by Twolewis — APPROVED** [review]
Please start a pull request to get these changes into o3de

**Comment by aefimov3** [comment]
@Twolewis I'm not sure if o3de wants it. This version has a hard limit for shader indices. For our game it is OK, but in general it is not. I can create a PR anyway, let they decide.

**Comment by aefimov3** [comment]
@JasonCarbonated the 128 limit is pretty low level. It is the number of shader options. Like color, opacity, texture tile offset, scale, etc. These are almost equal to material properties, so we have the limit of 128 material properties globally, for all the materials used.

**Comment by Twolewis** [comment]
> @Twolewis I'm not sure if o3de wants it. This version has a hard limit for shader indices. For our game it is OK, but in general it is not. I can create a PR anyway, let they decide.

Gotcha - then let's make it a variable sized limit (albeit using the bitflags).  Meaning, if you want 256 indices, then the container expands to 2x 128b and so on.  So you get the speed + flex for unlim. indices

**Pull request merged**
